(****************************************************************************


appres.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit appres;

interface

const

	DIALOG_1	=	1;
	CURSOR_2	=	2;
	CURSOR_1	=	1;
	DIALOG_2	=	2;
        
	DIALOG_3	=	3;
	IDC_PUSHBUTTON1	=	101;
	IDC_PUSHBUTTON2	=	102;
	IDC_PUSHBUTTON3	=	103;
	IDC_PUSHBUTTON4	=	104;
	IDC_PUSHBUTTON5	=	105;
	DIALOG_4	=	4;
	DIALOG_5	=	5;
	IDC_EDIT1	=	101;
	DIALOG_6	=	6;
	IDC_LISTBOX1	=	101;
	IDC_PUSHBUTTON6	=	101;
	IDC_PUSHBUTTON7	=	102;
	DIALOG_7	=	7;
	IDC_LTEXT1	=	106;
	IDC_LTEXT2	=	107;
implementation

end.
